// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWtnoX73fCzF_6VIayBwwn7Ur_jlTpb_U',
    appId: '1:95134775698:web:269963ba6915426c39694b',
    messagingSenderId: '95134775698',
    projectId: 'gemini-ai-chat-62174',
    authDomain: 'gemini-ai-chat-62174.firebaseapp.com',
    storageBucket: 'gemini-ai-chat-62174.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQnLp1YbWWKHlvumfFOa2Xi8RogQ7ZKVk',
    appId: '1:95134775698:android:721faaf1c6676d3939694b',
    messagingSenderId: '95134775698',
    projectId: 'gemini-ai-chat-62174',
    storageBucket: 'gemini-ai-chat-62174.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLCq-mmgeEp5nFYKwT2CJ3tkPx3E-lhs4',
    appId: '1:95134775698:ios:24863151ff91ca9739694b',
    messagingSenderId: '95134775698',
    projectId: 'gemini-ai-chat-62174',
    storageBucket: 'gemini-ai-chat-62174.appspot.com',
    iosBundleId: 'com.example.flutterGeminiAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLCq-mmgeEp5nFYKwT2CJ3tkPx3E-lhs4',
    appId: '1:95134775698:ios:24863151ff91ca9739694b',
    messagingSenderId: '95134775698',
    projectId: 'gemini-ai-chat-62174',
    storageBucket: 'gemini-ai-chat-62174.appspot.com',
    iosBundleId: 'com.example.flutterGeminiAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWtnoX73fCzF_6VIayBwwn7Ur_jlTpb_U',
    appId: '1:95134775698:web:e8a6ee69ac096e2239694b',
    messagingSenderId: '95134775698',
    projectId: 'gemini-ai-chat-62174',
    authDomain: 'gemini-ai-chat-62174.firebaseapp.com',
    storageBucket: 'gemini-ai-chat-62174.appspot.com',
  );
}
